name: PR_label_mandator

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check for the label
        if: >
          contains(github.event.pull_request.labels.*.name, 'bug') == false && 
          contains(github.event.pull_request.labels.*.name, 'documentation') == false && 
          contains(github.event.pull_request.labels.*.name, 'enhancement') == false &&
          contains(github.event.pull_request.labels.*.name, 'newlabel1') == false &&
          contains(github.event.pull_request.labels.*.name, 'newlabel2') == false
        run: exit 1
