name: lint_checker
on:
  push:
    branches: [ "feature", "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
      - name: Install flake8
        run: pip install flake8
      - name: Run a one-line script
        run: flake8 .
